name: Laravel

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  THIO-APP:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Install ZSH
      run: sudo apt-get install zsh
    - name: Copy .env
      run: cd src && php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Composer Dependencies
      run: cd src && composer install --no-interaction --prefer-dist --optimize-autoloader
    - name: Generate Key
      run: cd src && php artisan key:generate
    - name: Directory Permissions
      run: cd src && sudo chmod -R 777 storage bootstrap/cache
    - name: Create Database Folder
      run: cd src && mkdir -p database
    - name: Create Database File
      run: cd src && touch database/database.sqlite
    - name: Check Code via PHPCS
      run: cd src && ./vendor/bin/phpcs ./app
    # - name: Execute Tests (Unit and Feature Tests) via PHPUnit
    #   env:
    #     DB_CONNECTION: sqlite
    #     DB_DATABASE: database/database.sqlite
    #   run: cd src && ./vendor/bin/phpunit
